% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 27-Jun-2013 08:29:55
%  MATLAB version: 8.0.0.783 (R2012b)
% -------------------------------------------------------------------                               

% Controller constants
Kp = 0.0506692;
Ki = 0.362974;

% Controller sample time
Ts = 0.01;

% Lookup table scaling data
angle_sensor_range = [0.5 4.5];
pedal_sensor_range = [0 1];
uint_range_10bit = [0 1023];
normalized_range = [0 5];
digital_range = [0 1];
duty_range = [0 1];
direction_range = [-1 1];
direction_range_analog = [0 5];
duty_range_analog = [0 1];